apiVersion: v1
kind: Service
metadata: 
  name: todo-service
  namespace: django-ns
spec:
  type: NodePort
  selector:
    app: todo-app
  ports: 
    - port: 80
      targetPort: 8000
      nodePort: 30008

